version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/shipwreck-app-1.0-SNAPSHOT.war
